name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 3
          days-before-close: 4
          remove-issue-stale-when-updated: false
          ignore-issue-updates: true
          exempt-issue-labels: 'keep-open'
